spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 1234
    driverClassName: org.postgresql.Driver
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085