spring:
  profiles:
    active: local
  application:
    name: MedKit

  liquibase:
    change-log: db/changelog/liquibase-changeLog.xml
#    Liquibase turn on or off
    enabled: true

server:
  port: 8082