spring:
  datasource:
    username: admin
    password: 9654
    url: jdbc:postgresql://localhost:5433/medkit
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql