spring:
  datasource:
    driverClassName: org.postgresql.Driver
    #    deploy
    url: jdbc:postgresql://dpg-cifa91h8g3n3ipr1c4og-a/medkit
    #    local
#    url: jdbc:postgresql://dpg-cifa91h8g3n3ipr1c4og-a.oregon-postgres.render.com/medkit
    username: medkit_user
    password: hGgDOyeAyWqmLynH6yyaxUPLznVjdW39
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8085